#!/usr/bin/env python3
import os
import sys
import json
import yaml
import re
from datetime import datetime

def validate_flare_file(path):
    """Validate a single FLARE file with v4.0.56 high-fidelity rules"""
    errors = []
    warnings = []
    
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        
        # Find FLARE block
        lines = content.splitlines()
        flare_start = -1
        flare_end = -1
        
        for i, line in enumerate(lines):
            if line.strip() == "---" and i < 120:
                for j in range(i+1, min(i+100, len(lines))):
                    if lines[j].strip() == "---":
                        block_content = "\n".join(lines[i:j+1])
                        if "flare.headers:" in block_content:
                            flare_start, flare_end = i, j
                            break
                if flare_start != -1:
                    break
        
        if flare_start == -1:
            errors.append("No FLARE header found")
            return errors, warnings
        
        header_lines = lines[flare_start:flare_end+1]
        raw_yaml = "\n".join(header_lines).strip("---").strip()
        
        try:
            data = yaml.safe_load(raw_yaml)
        except Exception as e:
            errors.append(f"YAML Syntax Error: {e}")
            return errors, warnings

        # 1. ENFORCE CANONICAL ORDER
        keys = list(data.keys())
        expected_order = ["flame.init", "flare.headers", "flare.edges", "flare.footer", "flame.close"]
        
        # We only check order for keys that ARE present
        present_expected = [k for k in expected_order if k in keys]
        actual_order = [k for k in keys if k in expected_order]
        
        if present_expected != actual_order:
            errors.append(f"Header order mismatch. Expected: {', '.join(present_expected)}")

        # 2. TARGETED MANDATORY RULES (Safety Rule)
        headers = data.get("flare.headers", {})
        artifact_kind = headers.get("artifact_kind", "unknown")
        sys_version = str(headers.get("system_version", "0.0.0"))
        
        is_active_artifact = artifact_kind in ["prompt", "documentation_task", "agent_instruction", "artifact", "thread"]
        
        try:
            v_parts = [int(x) for x in re.findall(r'\d+', sys_version)]
            version_num = v_parts[0] * 10000 + v_parts[1] * 100 + (v_parts[2] if len(v_parts) > 2 else 0)
            
            if version_num >= 40055 and is_active_artifact:
                if "flame.init" not in data:
                    errors.append(f"Missing mandatory flame.init for active artifact_kind '{artifact_kind}' (v{sys_version})")
                if "flame.close" not in data:
                    errors.append(f"Missing mandatory flame.close for active artifact_kind '{artifact_kind}' (v{sys_version})")
        except:
            pass

        # 3. TYPED ACTIONS VALIDATION
        if "flame.init" in data:
            init = data["flame.init"]
            if not isinstance(init, dict):
                errors.append("flame.init must be an object")
            else:
                pre_actions = init.get("pre_actions", [])
                if not isinstance(pre_actions, list):
                    errors.append("flame.init.pre_actions must be a list")
                else:
                    for action in pre_actions:
                        if not isinstance(action, dict):
                            errors.append(f"Untyped action in flame.init: {action}. Actions must be objects.")

        if "flame.close" in data:
            close = data["flame.close"]
            if not isinstance(close, dict):
                errors.append("flame.close must be an object")
            else:
                post_actions = close.get("post_actions", [])
                if not isinstance(post_actions, list):
                    errors.append("flame.close.post_actions must be a list")
                else:
                    for action in post_actions:
                        if not isinstance(action, dict):
                            errors.append(f"Untyped action in flame.close: {action}. Actions must be objects.")

        # 4. PATH VALIDATION
        expected_path = os.path.relpath(path, ".").replace("\\", "/")
        actual_path = str(headers.get("file_path_from_root", "")).replace("\\", "/")
        if actual_path and actual_path != expected_path:
            errors.append(f"Path mismatch: {actual_path} != {expected_path}")

    except Exception as e:
        errors.append(f"Unexpected validation error: {e}")
    
    return errors, warnings

def main():
    ci_mode = "--ci" in sys.argv
    
    # Use flare_md_index.txt generated by flare_apply.py
    index_file = "tools/flare_md_index.txt"
    if not os.path.exists(index_file):
        # Fallback to manual scan if index doesn't exist
        paths = []
        for root, dirs, files in os.walk("."):
            if ".git" in dirs: dirs.remove(".git")
            for file in files:
                if file.endswith(".md"):
                    paths.append(os.path.join(root, file))
    else:
        with open(index_file, "r", encoding="utf-8") as f:
            paths = [line.strip() for line in f if line.strip()]
    
    total_errors = 0
    total_warnings = 0
    
    for path in paths:
        if not os.path.exists(path): continue
        
        errors, warnings = validate_flare_file(path)
        
        if errors:
            print(f"ERRORS in {path}:")
            for error in errors:
                print(f"  - {error}")
            total_errors += len(errors)
        
        if warnings:
            print(f"WARNINGS in {path}:")
            for warning in warnings:
                print(f"  - {warning}")
            total_warnings += len(warnings)
    
    print(f"\nValidation complete: {total_errors} errors, {total_warnings} warnings")
    
    if ci_mode and total_errors > 0:
        sys.exit(1)

if __name__ == "__main__":
    main()
