<?php
/**
 * Memory Export Service
 * 
 * Exports memory nodes and edges from database to filesystem as TOON files.
 * Implements PRD 38 requirement: database is source of truth, filesystem is read-only mirror.
 * 
 * @author Lupopedia Development Team
 * @version 4.0.89
 */

namespace App\Services;

use App\Database\DatabaseFactory;
use Exception;

class MemoryExportService
{
    private $db;
    private $exportPath;
    private $batchSize = 1000;
    
    public function __construct(DatabaseFactory $db, string $exportPath = null)
    {
        $this->db = $db;
        $this->exportPath = $exportPath ?? LupoConfig::get('memory.export_path', 'lupo-memory');
    }
    
    /**
     * Export all memory nodes and edges to filesystem
     * 
     * @param array $options Export options
     * @return array Export statistics
     */
    public function exportAll(array $options = []): array
    {
        $stats = [
            'nodes_exported' => 0,
            'edges_exported' => 0,
            'errors' => 0,
            'start_time' => time()
        ];
        
        try {
            // Export nodes first
            $stats['nodes_exported'] = $this->exportNodes($options);
            
            // Export edges
            $stats['edges_exported'] = $this->exportEdges($options);
            
            // Generate index files
            $this->generateIndexes();
            
        } catch (Exception $e) {
            $stats['errors']++;
            error_log("Memory export failed: " . $e->getMessage());
            throw $e;
        }
        
        $stats['duration'] = time() - $stats['start_time'];
        return $stats;
    }
    
    /**
     * Export memory nodes to TOON files
     * 
     * @param array $options
     * @return int Number of nodes exported
     */
    private function exportNodes(array $options): int
    {
        $exported = 0;
        $offset = 0;
        
        do {
            $nodes = $this->db->fetchAll(
                "SELECT * FROM lupo_memory_nodes 
                 WHERE is_deleted = 0 
                 ORDER BY memory_node_id 
                 LIMIT ? OFFSET ?",
                [$this->batchSize, $offset]
            );
            
            foreach ($nodes as $node) {
                $this->exportNode($node);
                $exported++;
            }
            
            $offset += $this->batchSize;
        } while (count($nodes) === $this->batchSize);
        
        return $exported;
    }
    
    /**
     * Export a single memory node to TOON file
     * 
     * @param array $node
     */
    private function exportNode(array $node): void
    {
        $toonData = [
            '_comment' => 'THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.',
            '_purpose' => 'Memory node export from database',
            '_source' => 'Generated by MemoryExportService',
            '_read_only' => true,
            'memory_node_id' => $node['memory_node_id'],
            'memory_key' => $node['memory_toon'],
            'memory_type' => $node['memory_type'],
            'owner_actor_id' => $node['owner_actor_id'],
            'channel_key' => $node['channel_key'],
            'trust_tier' => $node['trust_tier'],
            'properties_json' => $node['properties_json'] ? json_decode($node['properties_json'], true) : null,
            'created_ymdhis' => $node['created_ymdhis'],
            'updated_ymdhis' => $node['updated_ymdhis'],
            'is_deleted' => $node['is_deleted'],
            'deleted_ymdhis' => $node['deleted_ymdhis']
        ];
        
        $filePath = $this->getNodeFilePath($node['memory_toon']);
        $this->ensureDirectoryExists(dirname($filePath));
        
        // Convert to TOON format
        $toonContent = $this->toToon($toonData);
        file_put_contents($filePath, $toonContent);
    }
    
    /**
     * Export memory edges to TOON files
     * 
     * @param array $options
     * @return int Number of edges exported
     */
    private function exportEdges(array $options): int
    {
        $exported = 0;
        $offset = 0;
        
        do {
            $edges = $this->db->fetchAll(
                "SELECT * FROM lupo_memory_edges 
                 WHERE is_deleted = 0 
                 ORDER BY edge_id 
                 LIMIT ? OFFSET ?",
                [$this->batchSize, $offset]
            );
            
            foreach ($edges as $edge) {
                $this->exportEdge($edge);
                $exported++;
            }
            
            $offset += $this->batchSize;
        } while (count($edges) === $this->batchSize);
        
        return $exported;
    }
    
    /**
     * Export a single memory edge to TOON file
     * 
     * @param array $edge
     */
    private function exportEdge(array $edge): void
    {
        $toonData = [
            '_comment' => 'THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.',
            '_purpose' => 'Memory edge export from database',
            '_source' => 'Generated by MemoryExportService',
            '_read_only' => true,
            'edge_id' => $edge['edge_id'],
            'edge_type' => $edge['edge_type'],
            'from_memory_node_id' => $edge['from_memory_node_id'],
            'to_memory_node_id' => $edge['to_memory_node_id'],
            'weight' => $edge['weight'],
            'context_json' => $edge['context_json'] ? json_decode($edge['context_json'], true) : null,
            'created_ymdhis' => $edge['created_ymdhis'],
            'updated_ymdhis' => $edge['updated_ymdhis'],
            'is_deleted' => $edge['is_deleted'],
            'deleted_ymdhis' => $edge['deleted_ymdhis']
        ];
        
        $filePath = $this->getEdgeFilePath($edge['edge_id']);
        $this->ensureDirectoryExists(dirname($filePath));
        
        // Convert to TOON format
        $toonContent = $this->toToon($toonData);
        file_put_contents($filePath, $toonContent);
    }
    
    /**
     * Generate index files for faster lookups
     */
    private function generateIndexes(): void
    {
        // Generate node index by memory_key
        $nodeIndex = [];
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($this->exportPath . '/development/canonical')
        );
        
        foreach ($iterator as $file) {
            if ($file->getExtension() === 'toon' && strpos($file->getPathname(), '/edges/') === false) {
                $toonData = $this->parseToonFile($file->getPathname());
                if (isset($toonData['memory_key'])) {
                    $nodeIndex[$toonData['memory_key']] = $file->getPathname();
                }
            }
        }
        
        $indexFile = $this->exportPath . '/development/canonical/node_index.json';
        file_put_contents($indexFile, json_encode($nodeIndex, JSON_PRETTY_PRINT));
        
        // Generate edge type index
        $edgeTypeIndex = [];
        foreach ($iterator as $file) {
            if ($file->getExtension() === 'toon' && strpos($file->getPathname(), '/edges/') !== false) {
                $toonData = $this->parseToonFile($file->getPathname());
                if (isset($toonData['edge_type'])) {
                    $edgeType = $toonData['edge_type'];
                    if (!isset($edgeTypeIndex[$edgeType])) {
                        $edgeTypeIndex[$edgeType] = [];
                    }
                    $edgeTypeIndex[$edgeType][] = $file->getPathname();
                }
            }
        }
        
        $edgeIndexFile = $this->exportPath . '/development/canonical/edge_type_index.json';
        file_put_contents($edgeIndexFile, json_encode($edgeTypeIndex, JSON_PRETTY_PRINT));
    }
    
    /**
     * Get filesystem path for a memory node
     * 
     * @param string $memoryKey
     * @return string
     */
    private function getNodeFilePath(string $memoryKey): string
    {
        // Parse memory key: lupo-memory/development/canonical/1026/04/slug.toon
        $parts = explode('/', $memoryKey);
        if (count($parts) < 5) {
            throw new Exception("Invalid memory key format: $memoryKey");
        }
        
        $slug = end($parts);
        return "{$this->exportPath}/development/canonical/1026/04/{$slug}.toon";
    }
    
    /**
     * Get filesystem path for a memory edge
     * 
     * @param int $edgeId
     * @return string
     */
    private function getEdgeFilePath(int $edgeId): string
    {
        return "{$this->exportPath}/development/canonical/edges/{$edgeId}.toon";
    }
    
    /**
     * Ensure directory exists
     * 
     * @param string $dir
     */
    private function ensureDirectoryExists(string $dir): void
    {
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
    }
    
    /**
     * Convert array to TOON format
     * 
     * @param array $data
     * @return string
     */
    private function toToon(array $data): string
    {
        $lines = [];
        foreach ($data as $key => $value) {
            if (str_starts_with($key, '_')) {
                // Comment line
                $lines[] = "{$key}: {$value}";
            } elseif (is_array($value)) {
                // Nested array
                $lines[] = "{$key}:";
                foreach ($value as $subKey => $subValue) {
                    if (is_array($subValue)) {
                        $lines[] = "  {$subKey}:";
                        foreach ($subValue as $k => $v) {
                            $lines[] = "    {$k}: {$this->formatValue($v)}";
                        }
                    } else {
                        $lines[] .= "  {$subKey}: {$this->formatValue($subValue)}";
                    }
                }
            } else {
                $lines[] = "{$key}: {$this->formatValue($value)}";
            }
        }
        return implode("\n", $lines) . "\n";
    }
    
    /**
     * Format value for TOON output
     * 
     * @param mixed $value
     * @return string
     */
    private function formatValue($value): string
    {
        if (is_null($value)) {
            return 'null';
        } elseif (is_bool($value)) {
            return $value ? 'true' : 'false';
        } elseif (is_string($value) && (str_contains($value, ' ') || str_contains($value, ':'))) {
            return '"' . str_replace('"', '\\"', $value) . '"';
        } else {
            return (string) $value;
        }
    }
    
    /**
     * Parse TOON file (basic implementation)
     * 
     * @param string $filePath
     * @return array
     */
    private function parseToonFile(string $filePath): array
    {
        $content = file_get_contents($filePath);
        $data = [];
        $lines = explode("\n", $content);
        
        foreach ($lines as $line) {
            $line = trim($line);
            if (empty($line) || str_starts_with($line, '#')) {
                continue;
            }
            
            if (str_contains($line, ':')) {
                [$key, $value] = explode(':', $line, 2);
                $key = trim($key);
                $value = trim($value);
                
                // Basic type conversion
                if ($value === 'null') {
                    $data[$key] = null;
                } elseif ($value === 'true') {
                    $data[$key] = true;
                } elseif ($value === 'false') {
                    $data[$key] = false;
                } elseif (is_numeric($value)) {
                    $data[$key] = is_float($value) ? (float) $value : (int) $value;
                } else {
                    $data[$key] = $value;
                }
            }
        }
        
        return $data;
    }
    
    /**
     * Export incremental changes since last export
     * 
     * @param int $lastExportTime
     * @return array
     */
    public function exportIncremental(int $lastExportTime): array
    {
        $stats = [
            'nodes_exported' => 0,
            'edges_exported' => 0,
            'errors' => 0
        ];
        
        // Export updated nodes
        $nodes = $this->db->fetchAll(
            "SELECT * FROM lupo_memory_nodes 
             WHERE updated_ymdhis > ? AND is_deleted = 0",
            [$lastExportTime]
        );
        
        foreach ($nodes as $node) {
            try {
                $this->exportNode($node);
                $stats['nodes_exported']++;
            } catch (Exception $e) {
                $stats['errors']++;
                error_log("Failed to export node {$node['memory_node_id']}: " . $e->getMessage());
            }
        }
        
        // Export updated edges
        $edges = $this->db->fetchAll(
            "SELECT * FROM lupo_memory_edges 
             WHERE updated_ymdhis > ? AND is_deleted = 0",
            [$lastExportTime]
        );
        
        foreach ($edges as $edge) {
            try {
                $this->exportEdge($edge);
                $stats['edges_exported']++;
            } catch (Exception $e) {
                $stats['errors']++;
                error_log("Failed to export edge {$edge['edge_id']}: " . $e->getMessage());
            }
        }
        
        // Regenerate indexes
        $this->generateIndexes();
        
        return $stats;
    }
    
    /**
     * Validate export integrity
     * 
     * @return array Validation results
     */
    public function validateExport(): array
    {
        $results = [
            'node_count_match' => false,
            'edge_count_match' => false,
            'missing_files' => [],
            'extra_files' => []
        ];
        
        // Count in database
        $dbNodeCount = $this->db->fetchOne(
            "SELECT COUNT(*) FROM lupo_memory_nodes WHERE is_deleted = 0"
        );
        $dbEdgeCount = $this->db->fetchOne(
            "SELECT COUNT(*) FROM lupo_memory_edges WHERE is_deleted = 0"
        );
        
        // Count in filesystem
        $fsNodeCount = $this->countFiles($this->exportPath . '/development/canonical/1026/04', 'toon');
        $fsEdgeCount = $this->countFiles($this->exportPath . '/development/canonical/edges', 'toon');
        
        $results['node_count_match'] = ($dbNodeCount == $fsNodeCount);
        $results['edge_count_match'] = ($dbEdgeCount == $fsEdgeCount);
        $results['db_nodes'] = $dbNodeCount;
        $results['fs_nodes'] = $fsNodeCount;
        $results['db_edges'] = $dbEdgeCount;
        $results['fs_edges'] = $fsEdgeCount;
        
        return $results;
    }
    
    /**
     * Count files in directory
     * 
     * @param string $dir
     * @param string $extension
     * @return int
     */
    private function countFiles(string $dir, string $extension): int
    {
        if (!is_dir($dir)) {
            return 0;
        }
        
        return count(glob($dir . '/*.' . $extension));
    }
}
