#!/usr/bin/env python3

# PRD 84 mapping
mapping = {
    '00_A': '00_A_FORBIDDEN_AND_WHY',
    '00_B': '00_B_SYSTEM_CANONICAL_EXPLANATION',
    '00_C': '00_C_ROOT_CONSTITUTIONAL_SYSTEM_REQUIREMENTS',
    '16_A': '16_A_HEADER_TEMPLATE_22_FIELDS',
    '16_B': '16_B_ATOMS_SYSTEM_AND_GLOBAL_CONSTANTS',
    '16_C': '16_C_LUPOPEDIA_HEADERS',
    '16_D': '16_D_LUPOPEDIA_HEADERS_EXAMPLES',
    '16_E': '16_E_LUPOPEDIA_HEADERS_MIGRATION',
    '33_A': '33_A_SOFTACULOUS_CERTIFICATION_4_1_0_GATE',
    '84_A': '84_A_PRD_NUMBER_ALLOCATION_DOCTRINE'
}

# Extract PRD clusters from the grep output
prd_clusters = {
    '00_A_FORBIDDEN_AND_WHY.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS_26_A_FIVE_LAYER_DOCUMENTATION_ARCHITECTURE',
    '99_A_LIMITS_FOR_EVERYTHING_AND_WHY.md': '00_A_FORBIDDEN_AND_WHY_99_A_LIMITS_FOR_EVERYTHING_AND_WHY',
    '98_B_THE_CAPTAINS_LOG_HUMAN_ONLY_ENTERTAINMENT_LAYER.md': '00_A_FORBIDDEN_AND_WHY_98_B_CAPTAINS_LOG',
    '98_A_WHY_FILES_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_49_A_QUESTIONS_AND_ANSWERS_98_A_WHY_FILES',
    '97_A_THE_WHY_FILES_THE_TRUTH_IS_OUT_THERE.md': '00_A_FORBIDDEN_AND_WHY_97_A_THE_WHY_FILES_THE_TRUTH_IS_OUT_THERE',
    '86_A_IMMUNE_SYSTEM_HEADER_ENFORCEMENT.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS_86_A_IMMUNE_SYSTEM',
    '85_A_IMPORTING_CRAFTY_SYNTAX_SEMANTICS_AND_USERS.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_79_A_INSTALL_SEED_85_A_CRAFTY_SYNTAX',
    '84_A_PRD_NUMBER_ALLOCATION_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_84_A_PRD_NUMBER_ALLOCATION_DOCTRINE',
    '83_A_MEMORY_TOON_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_83_A_MEMORY_TOON_DOCTRINE',
    '82_A_HERMES_MESSAGE_ROUTING_MEMORY_GATEWAY.md': '00_A_FORBIDDEN_AND_WHY_00_C_ROOT_CONSTITUTIONAL_SYSTEM_REQUIREMENTS_82_A_HERMES_MESSAGE_ROUTING_MEMORY_GATEWAY',
    '80_A_DATABASE_DESIGN_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_80_A_DATABASE_DESIGN_DOCTRINE',
    '79_A_INSTALL_SEED_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_79_A_INSTALL_SEED',
    '78_A_CLI_INTERFACE_PRD.md': '00_A_FORBIDDEN_AND_WHY_78_A_CLI_INTERFACE_PRD',
    '77_A_THREAD_GRADUATION_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_77_A_THREAD_GRADUATION_DOCTRINE',
    '76_A_VSX_EXTENSION.md': '00_A_FORBIDDEN_AND_WHY_76_A_VSX_EXTENSION',
    '75_A_TEMPORAL_SYSTEM.md': '00_A_FORBIDDEN_AND_WHY_75_A_TEMPORAL_SYSTEM',
    '74_A_GOVERNANCE_RULES.md': '00_A_FORBIDDEN_AND_WHY_74_A_GOVERNANCE_RULES',
    '73_A_COLLECTIONS_NAVIGATION.md': '00_A_FORBIDDEN_AND_WHY_73_A_COLLECTIONS_NAVIGATION',
    '72_A_TAGS_METADATA.md': '00_A_FORBIDDEN_AND_WHY_72_A_TAGS_METADATA',
    '71_A_TRUTH_KNOWLEDGE.md': '00_A_FORBIDDEN_AND_WHY_71_A_TRUTH_KNOWLEDGE',
    '61_A_DOCTRINE_CONSOLIDATION_SHORTHAND_COMPILER.md': '00_A_FORBIDDEN_AND_WHY_61_A_DOCTRINE_CONSOLIDATION_SHORTHAND_COMPILER',
    '70_A_DATA_MODEL.md': '00_A_FORBIDDEN_AND_WHY_70_A_DATA_MODEL',
    '60_A_ORCHESTRATOR_SCHEDULER.md': '00_A_FORBIDDEN_AND_WHY_60_A_ORCHESTRATOR_SCHEDULER',
    '58_A_TRANSCRIPT_FILTER.md': '00_A_FORBIDDEN_AND_WHY_58_A_TRANSCRIPT_FILTER',
    '56_A_PROBE_HARNESS_V2.md': '00_A_FORBIDDEN_AND_WHY_56_A_PROBE_HARNESS_V2',
    '55_A_WORKFLOW_AND_CHECKPOINT_MODEL.md': '00_A_FORBIDDEN_AND_WHY_55_A_WORKFLOW_AND_CHECKPOINT_MODEL',
    '54_A_ACTOR_COMPLIANCE.md': '00_A_FORBIDDEN_AND_WHY_54_A_ACTOR_COMPLIANCE',
    '53_A_RUNTIME_GUARD.md': '00_A_FORBIDDEN_AND_WHY_53_A_RUNTIME_GUARD',
    '52_A_MEMORY_GRAPH_FOCUS_MANIFEST.md': '00_A_FORBIDDEN_AND_WHY_52_A_MEMORY_GRAPH_FOCUS_MANIFEST',
    '51_A_MEMORY_GRAPH_AS_SOURCE_OF_TRUTH.md': '00_A_FORBIDDEN_AND_WHY_51_A_MEMORY_GRAPH_AS_SOURCE_OF_TRUTH',
    '50_B_CRAFTY_SYNTAX_MODIFIED_FEATURES.md': '00_A_FORBIDDEN_AND_WHY_50_B_CRAFTY_SYNTAX_MODIFIED_FEATURES',
    '50_A_CRAFTY_SYNTAX_FEATURES_IN_LUPOPEDIA.md': '00_A_FORBIDDEN_AND_WHY_50_A_CRAFTY_SYNTAX_FEATURES_IN_LUPOPEDIA',
    '50_A_AGENT_COORDINATION_PROTOCOL.md': '00_A_FORBIDDEN_AND_WHY_50_A_AGENT_COORDINATION_PROTOCOL',
    '49_A_QUESTIONS_AND_ANSWERS_SYSTEM.md': '00_A_FORBIDDEN_AND_WHY_49_A_QUESTIONS_AND_ANSWERS',
    '48_A_MANUAL_ORCHESTRATION_GAP.md': '00_A_FORBIDDEN_AND_WHY_16_C_HEADERS_48_A_MANUAL_ORCHESTRATION_GAP',
    '47_A_ACTOR_RUNTIME_DIRECTORY_STRUCTURE.md': '00_A_FORBIDDEN_AND_WHY_47_A_ACTOR_RUNTIME_DIRECTORY_STRUCTURE',
    '46_A_ACTOR_GATEWAY_TYPES.md': '00_A_FORBIDDEN_AND_WHY_46_A_ACTOR_GATEWAY_TYPES',
    '45_A_TEMPLATE_FIRST_STAGED_UI_WORKFLOW.md': '00_A_FORBIDDEN_AND_WHY_45_A_TEMPLATE_FIRST_STAGED_UI_WORKFLOW',
    '44_A_SESSION_CONFIG_AND_TRANSCRIPT.md': '00_A_FORBIDDEN_AND_WHY_44_A_SESSION_CONFIG_AND_TRANSCRIPT',
    '43_A_PARENT_CHILD_TRUST_LADDER.md': '00_A_FORBIDDEN_AND_WHY_43_A_PARENT_CHILD_TRUST_LADDER',
    '42_A_CONTENT_SEEDING_AND_TRUTH_TABLES.md': '00_A_FORBIDDEN_AND_WHY_42_A_CONTENT_SEEDING_AND_TRUTH_TABLES',
    '41_A_CAPTAIN_WOLFIE_IDENTITY.md': '00_A_FORBIDDEN_AND_WHY_41_A_CAPTAIN_WOLFIE_IDENTITY',
    '40_A_VERSIONING_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_40_A_VERSIONING_DOCTRINE',
    '38_A_MEMORY_UNIFICATION.md': '00_A_FORBIDDEN_AND_WHY_38_A_MEMORY_UNIFICATION',
    '37_A_KAIROS_CHANNEL_MEMORY_CONSOLIDATION.md': '00_A_FORBIDDEN_AND_WHY_37_A_KAIROS_CHANNEL_MEMORY_CONSOLIDATION',
    '36_A_ROSE_MULTI_PERSONA_SYNTHETIC_DIALOG.md': '00_A_FORBIDDEN_AND_WHY_36_A_ROSE_MULTI_PERSONA_SYNTHETIC_DIALOG',
    '35_A_MOBILE_NATIVE_APP_SEPARATION.md': '00_A_FORBIDDEN_AND_WHY_35_A_MOBILE_NATIVE_APP_SEPARATION',
    '34_A_FEDERATION_NODE_SEMANTIC_NETWORK.md': '00_A_FORBIDDEN_AND_WHY_34_A_FEDERATION_NODE_SEMANTIC_NETWORK',
    '33_A_SOFTACULOUS_CERTIFICATION_4_1_0_GATE.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS_33_A_SOFTACULOUS_CERTIFICATION_4_1_0_GATE',
    '32_A_ACTOR_AUTHORITY_AGENT_ROLES.md': '00_A_FORBIDDEN_AND_WHY_32_A_ACTOR_AUTHORITY_AGENT_ROLES',
    '31_A_IMPLEMENTATION_FOLDER_GUIDELINES.md': '00_A_FORBIDDEN_AND_WHY_31_A_IMPLEMENTATION_FOLDER_GUIDELINES',
    '30_A_CHANNEL_USAGE_PATTERNS.md': '00_A_FORBIDDEN_AND_WHY_30_A_CHANNEL_USAGE_PATTERNS',
    '29_A_PROJECT_STRUCTURE.md': '00_A_FORBIDDEN_AND_WHY_29_A_PROJECT_STRUCTURE',
    '28_A_SEMANTIC_MONITORING_WIDGET.md': '00_A_FORBIDDEN_AND_WHY_28_A_SEMANTIC_MONITORING_WIDGET',
    '27_A_INSTALLER_REQUIREMENTS.md': '00_A_FORBIDDEN_AND_WHY_27_A_INSTALLER_REQUIREMENTS',
    '26_A_FIVE_LAYER_DOCUMENTATION_ARCHITECTURE.md': '00_A_FORBIDDEN_AND_WHY_26_A_FIVE_LAYER_DOCUMENTATION_ARCHITECTURE',
    '25_A_DEPARTMENTS_SYSTEM.md': '00_A_FORBIDDEN_AND_WHY_25_A_DEPARTMENTS_SYSTEM',
    '24_A_ACTOR_ONBOARDING_FLOW.md': '00_A_FORBIDDEN_AND_WHY_24_A_ACTOR_ONBOARDING_FLOW',
    '23_A_HEALTH_CHECK_ASCLEPIUS_PRD.md': '00_A_FORBIDDEN_AND_WHY_23_A_HEALTH_CHECK_ASCLEPIUS_PRD',
    '22_A_WEB_NAVIGATION_ARCHITECTURE.md': '00_A_FORBIDDEN_AND_WHY_22_A_WEB_NAVIGATION_ARCHITECTURE',
    '21_A_SEMANTIC_NAVBAR.md': '00_A_FORBIDDEN_AND_WHY_21_A_SEMANTIC_NAVBAR',
    '20_A_FEDERATION_INTAKE_DOCTRINE.md': '00_A_FORBIDDEN_AND_WHY_20_A_FEDERATION_INTAKE_DOCTRINE',
    '19_A_GARBAGE_COLLECTION_SYSTEM.md': '00_A_FORBIDDEN_AND_WHY_19_A_GARBAGE_COLLECTION_SYSTEM',
    '18_A_CHANNEL_CHAT_DISPLAY.md': '00_A_FORBIDDEN_AND_WHY_18_A_CHANNEL_CHAT_DISPLAY',
    '17_A_DECISIONS_FORMAT.md': '00_A_FORBIDDEN_AND_WHY_17_A_DECISIONS_FORMAT',
    '16_E_LUPOPEDIA_HEADERS_MIGRATION.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS_16_D_MIGRATION',
    '16_D_LUPOPEDIA_HEADERS_EXAMPLES.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS_16_D_EXAMPLES',
    '16_C_LUPOPEDIA_HEADERS.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS',
    '16_B_ATOMS_SYSTEM_AND_GLOBAL_CONSTANTS.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS',
    '16_A_HEADER_TEMPLATE_22_FIELDS.md': '00_A_FORBIDDEN_AND_WHY_16_B_ATOMS_16_C_HEADERS_16_A_TEMPLATE_16_D_EXAMPLES',
    '15_A_ACTORS.md': '00_A_FORBIDDEN_AND_WHY_15_A_ACTORS',
    '14_A_SYSTEM_OPERATIONS.md': '00_A_FORBIDDEN_AND_WHY_14_A_SYSTEM_OPERATIONS',
    '13_A_CRAFTY_INTEGRATION.md': '00_A_FORBIDDEN_AND_WHY_13_A_CRAFTY_INTEGRATION',
    '12_B_TOKEN_GOVERNANCE_SECTION.md': '00_A_FORBIDDEN_AND_WHY_12_B_TOKEN_GOVERNANCE_SECTION',
    '12_A_API_INTEGRATION.md': '00_A_FORBIDDEN_AND_WHY_12_A_API_INTEGRATION',
    '11_A_ANALYTICS_TRACKING.md': '00_A_FORBIDDEN_AND_WHY_11_A_ANALYTICS_TRACKING',
    '10_A_TASKS_WORKFLOW.md': '00_A_FORBIDDEN_AND_WHY_10_A_TASKS_WORKFLOW',
    '09_A_FEDERATION_SYNC.md': '00_A_FORBIDDEN_AND_WHY_09_A_FEDERATION_SYNC',
    '08_C_AGENT_PAIRING_LEARNING_COLLECTIONS_TRANSCRIPTS_TOONS.md': '00_A_FORBIDDEN_AND_WHY_08_A_CORE_AGENTS_SYSTEM_08_B_AGENT_MAP_08_C_AGENT_PAIRING_LEARNING_COLLECTIONS_TRANSCRIPTS_TOONS',
    '08_B_AGENT_MAP.md': '00_A_FORBIDDEN_AND_WHY_08_A_CORE_AGENTS_SYSTEM_08_B_AGENT_MAP',
    '08_A_CORE_AGENTS_SYSTEM.md': '00_A_FORBIDDEN_AND_WHY_00_C_ROOT_CONSTITUTIONAL_SYSTEM_REQUIREMENTS_08_A_CORE_AGENTS_SYSTEM',
    '07_A_AGENTS_FAUCETS.md': '00_A_FORBIDDEN_AND_WHY_07_A_AGENTS_FAUCETS',
    '06_A_CONTENT_MANAGEMENT.md': '00_A_FORBIDDEN_AND_WHY_06_A_CONTENT_MANAGEMENT',
    '05_A_AUTH_USER_ACTOR_AGENT_TRANSFORMATION.md': '00_A_FORBIDDEN_AND_WHY_05_A_AUTH_USER_ACTOR_AGENT_TRANSFORMATION',
    '04_A_LUPOPEDIA_JS_FOUNDATION.md': '00_A_FORBIDDEN_AND_WHY_04_A_LUPOPEDIA_JS_FOUNDATION',
    '03_A_GOALS_AND_SUCCESS_CRITERIA.md': '00_A_FORBIDDEN_AND_WHY_03_A_GOALS_AND_SUCCESS_CRITERIA',
    '02_D_CHANNELS_MOCKUPS_MODULES.md': '00_A_FORBIDDEN_AND_WHY_02_D_CHANNELS_MOCKUPS_MODULES',
    '02_C_CHANNELS_DISCUSSIONS.md': '00_A_FORBIDDEN_AND_WHY_02_C_CHANNELS_DISCUSSIONS',
    '02_B_CHANNELS_DB_OVERVIEW.md': '00_A_FORBIDDEN_AND_WHY_02_B_CHANNELS_DB_OVERVIEW',
    '02_A_CHANNELS_DB_DESIGN.md': '00_A_FORBIDDEN_AND_WHY_02_A_CHANNELS_DB_DESIGN',
    '01_A_CORE_IDENTITY.md': '00_A_FORBIDDEN_AND_WHY_01_A_CORE_IDENTITY',
    '00_C_ROOT_CONSTITUTIONAL_SYSTEM_REQUIREMENTS.md': '00_A_FORBIDDEN_AND_WHY_00_C_ROOT_CONSTITUTIONAL_SYSTEM_REQUIREMENTS',
    '00_B_SYSTEM_CANONICAL_EXPLANATION.md': '00_A_FORBIDDEN_AND_WHY_00_B_SYSTEM_CANONICAL_EXPLANATION',
    '00_D_SYSTEM_POLICY_AND_RULES.md': '00_A_FORBIDDEN_AND_WHY_00_D_SYSTEM_POLICY_AND_RULES'
}

# Function to check if all PRDs in cluster have mappings
def can_use_shorthand(cluster):
    if not cluster:
        return False, 'empty cluster'
    
    # Split by underscore
    parts = cluster.split('_')
    prds = []
    i = 0
    while i < len(parts):
        if i + 1 < len(parts) and parts[i].isdigit() and parts[i+1].isalpha():
            prds.append(f'{parts[i]}_{parts[i+1]}')
            i += 2
        else:
            i += 1
    
    # Check each PRD
    for prd in prds:
        if prd not in mapping:
            return False, f'mapping missing for {prd}'
    
    return True, ''

# Analyze each PRD
safe_files = []
unsafe_files = []

for filename, cluster in prd_clusters.items():
    # Remove quotes if present
    cluster = cluster.strip('"')
    
    can_use, reason = can_use_shorthand(cluster)
    
    if can_use:
        # Convert to shorthand
        parts = cluster.split('_')
        shorthand_parts = []
        i = 0
        while i < len(parts):
            if i + 1 < len(parts) and parts[i].isdigit() and parts[i+1].isalpha():
                shorthand_parts.append(f'{parts[i]}_{parts[i+1]}')
                i += 2
            else:
                # Add the rest as is
                shorthand_parts.append('_'.join(parts[i:]))
                break
        shorthand_cluster = '_'.join(shorthand_parts)
        safe_files.append((filename, cluster, shorthand_cluster))
    else:
        unsafe_files.append((filename, cluster, reason))

# Print results
print('=== SAFE TO CONVERT TO SHORTHAND ===')
for filename, current, proposed in safe_files:
    print(f'FILE: {filename}')
    print(f'CURRENT_CLUSTER: {current}')
    print(f'CAN_USE_SHORTHAND: YES')
    print(f'PROPOSED_CLUSTER: {proposed}')
    print()

print('=== UNSAFE TO CONVERT ===')
for filename, current, reason in unsafe_files:
    print(f'FILE: {filename}')
    print(f'CURRENT_CLUSTER: {current}')
    print(f'CAN_USE_SHORTHAND: NO')
    print(f'REASON: {reason}')
    print()

print(f'=== SUMMARY ===')
print(f'Safe to convert: {len(safe_files)} files')
print(f'Unsafe to convert: {len(unsafe_files)} files')
