-- =====================================================
-- LupoPedia Migration - Part 4: Content & Collections Tables
-- Based on TOON schema only - HERITAGE-SAFE MODE
-- =====================================================

CREATE TABLE IF NOT EXISTS `lupo_contents` (
    `content_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key for content',
    `content_parent_id` bigint COMMENT 'Parent content ID for hierarchical relationships',
    `federation_node_id` bigint DEFAULT 1 COMMENT 'Domain scope, NULL for global content',
    `group_id` bigint COMMENT 'Optional group restriction',
    `user_id` bigint COMMENT 'Author of the content',
    `title` varchar(255) NOT NULL COMMENT 'Content title',
    `slug` varchar(255) NOT NULL COMMENT 'URL-friendly identifier, unique within domain',
    `description` text COMMENT 'Short summary or teaser',
    `seo_keywords` varchar(500),
    `body` longtext COMMENT 'Main content body',
    `content_type` varchar(50) DEFAULT 'article' COMMENT 'Type of content (article, page, post, etc.)',
    `format` varchar(20) DEFAULT 'html' COMMENT 'Content format (html, markdown, etc.)',
    `content_url` varchar(2000) COMMENT 'content URL if content is referenced by url such as lupopedia.com/content/lupopedia',
    `default_collection_id` bigint COMMENT 'Default collection ID',
    `source_url` varchar(2000) COMMENT 'Original source URL if content is imported',
    `source_title` varchar(500) COMMENT 'Title of the source',
    `is_template` tinyint NOT NULL DEFAULT 0 COMMENT '1 = template, 0 = regular content',
    `status` enum('draft','published','archived') DEFAULT 'draft' COMMENT 'Publication status',
    `visibility` enum('public','private','unlisted') DEFAULT 'public' COMMENT 'Visibility level',
    `view_count` int DEFAULT 0 COMMENT 'Number of views',
    `share_count` int DEFAULT 0 COMMENT 'Number of shares',
    `created_ymdhis` bigint NOT NULL COMMENT 'UTC YYYYMMDDHHMMSS when created',
    `utc_cycle` enum('creative','responsible') NOT NULL,
    `triage_status` enum('untriaged','keeper','fragment','duplicate','trash') NOT NULL DEFAULT 'untriaged',
    `triage_notes` text,
    `updated_ymdhis` bigint NOT NULL COMMENT 'UTC YYYYMMDDHHMMSS when last updated',
    `is_deleted` tinyint NOT NULL DEFAULT 0 COMMENT '1 = deleted, 0 = not deleted',
    `is_active` tinyint NOT NULL DEFAULT 1 COMMENT '1 = active, 0 = not active',
    `deleted_ymdhis` bigint COMMENT 'UTC YYYYMMDDHHMMSS when deleted',
    `content_sections` json COMMENT 'Cached list of section anchors extracted from the content body',
    `version_number` int NOT NULL DEFAULT 1 COMMENT 'Monotonic version number for the live content row',
    PRIMARY KEY (`content_id`),
    KEY `idx_federation_node_id` (`federation_node_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_slug` (`slug`),
    KEY `idx_content_type` (`content_type`),
    KEY `idx_status` (`status`),
    KEY `idx_visibility` (`visibility`),
    KEY `idx_created_ymdhis` (`created_ymdhis`),
    KEY `idx_updated_ymdhis` (`updated_ymdhis`),
    KEY `idx_is_deleted` (`is_deleted`),
    KEY `idx_is_active` (`is_active`),
    KEY `idx_default_collection_id` (`default_collection_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lupo_collections` (
    `collection_id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key for collection',
    `federations_node_id` bigint NOT NULL COMMENT 'Domain this collection belongs to',
    `user_id` bigint COMMENT 'Owner of this collection, if user-owned',
    `group_id` bigint COMMENT 'Owning group, if group-owned',
    `name` varchar(255) NOT NULL COMMENT 'Display name of the collection',
    `slug` varchar(100) NOT NULL COMMENT 'URL-friendly identifier, unique per domain',
    `color` char(6) DEFAULT '666666' COMMENT 'Hex color code for the collection (6 hex characters, no hash)',
    `description` text COMMENT 'Optional description of the collection',
    `sort_order` int DEFAULT 0 COMMENT 'Manual sort order within parent container',
    `properties` text COMMENT 'JSON-encoded key-value store',
    `published_ymdhis` bigint COMMENT 'UTC YYYYMMDDHHMMSS when published',
    `created_ymdhis` bigint NOT NULL COMMENT 'UTC YYYYMMDDHHMMSS when created',
    `updated_ymdhis` bigint NOT NULL COMMENT 'UTC YYYYMMDDHHMMSS when last updated',
    `is_deleted` tinyint NOT NULL DEFAULT 0 COMMENT '1 = deleted, 0 = not deleted',
    `deleted_ymdhis` bigint COMMENT 'UTC YYYYMMDDHHMMSS when deleted',
    `parent_id` bigint,
    PRIMARY KEY (`collection_id`),
    UNIQUE KEY `unique_collection_slug_domain` (`federations_node_id`, `slug`),
    KEY `idx_created_ymdhis` (`created_ymdhis`),
    KEY `idx_domain` (`federations_node_id`),
    KEY `idx_group` (`group_id`),
    KEY `idx_is_deleted` (`is_deleted`),
    KEY `idx_name` (`name`),
    KEY `idx_sort_order` (`sort_order`),
    KEY `idx_updated_ymdhis` (`updated_ymdhis`),
    KEY `idx_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lupo_collection_tabs` (
    `tab_id` bigint NOT NULL AUTO_INCREMENT,
    `collection_id` bigint NOT NULL,
    `tab_name` varchar(255) NOT NULL,
    `tab_key` varchar(100) NOT NULL,
    `tab_order` int DEFAULT 0,
    `tab_config` json,
    `created_ymdhis` bigint NOT NULL,
    `updated_ymdhis` bigint NOT NULL,
    `is_deleted` tinyint NOT NULL DEFAULT 0,
    PRIMARY KEY (`tab_id`),
    KEY `idx_collection_id` (`collection_id`),
    KEY `idx_tab_key` (`tab_key`),
    KEY `idx_tab_order` (`tab_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lupo_actor_collections` (
    `actor_collection_id` bigint NOT NULL AUTO_INCREMENT,
    `actor_id` bigint NOT NULL COMMENT 'User, group, agent, or persona',
    `collection_id` bigint NOT NULL COMMENT 'Collection actor has access to',
    `access_level` enum('owner','write','read') NOT NULL DEFAULT 'read',
    `created_ymdhis` bigint NOT NULL COMMENT 'UTC YYYYMMDDHHMMSS when granted',
    `updated_ymdhis` bigint COMMENT 'UTC YYYYMMDDHHMMSS when updated',
    `is_deleted` tinyint NOT NULL DEFAULT 0,
    `deleted_ymdhis` bigint,
    `persistent_identity_json` json COMMENT 'RSHAP persistent identity metadata',
    `identity_signature` varchar(255) COMMENT 'Unique identity signature for handshake verification',
    `trust_level` enum('system','verified','standard','restricted','untrusted') DEFAULT 'standard' COMMENT 'Trust level for multi-agent interactions',
    `emotional_geometry_baseline` json COMMENT 'Baseline emotional geometry for agent interactions',
    `doctrine_alignment_version` varchar(20) DEFAULT '4.0.72' COMMENT 'Version of doctrine this actor aligns with',
    PRIMARY KEY (`actor_collection_id`),
    KEY `idx_access_level` (`access_level`),
    KEY `idx_actor` (`actor_id`),
    KEY `idx_collection` (`collection_id`),
    KEY `idx_created_ymdhis` (`created_ymdhis`),
    KEY `idx_identity_signature` (`identity_signature`),
    KEY `idx_is_deleted` (`is_deleted`),
    KEY `idx_trust_level` (`trust_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
