CREATE TABLE lupo_registry (
  registry_id bigint NOT NULL AUTO_INCREMENT,
  unified_registry_id bigint NOT NULL DEFAULT 0,
  entity_type varchar(50) NOT NULL,
  entity_index_id bigint NOT NULL DEFAULT 0,
  entity_index bigint NOT NULL DEFAULT 0,
  federation_node_id bigint NOT NULL DEFAULT 0,
  reserved_ymdhis bigint NOT NULL DEFAULT 0,
  metadata text,
  entity_key varchar(255) DEFAULT NULL,
  entity_name varchar(255) DEFAULT NULL,
  entity_table varchar(255) DEFAULT NULL,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  updated_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint DEFAULT NULL,
  is_active tinyint NOT NULL DEFAULT 1,
  is_kernel tinyint NOT NULL DEFAULT 0,
  metadata_json text,
  PRIMARY KEY (registry_id)
);
