INSERT INTO lupo_edges (
    left_object_type,
    left_object_id,
    right_object_type,
    right_object_id,
    edge_type,
    channel_id,
    channel_key,
    weight_score,
    sort_num,
    actor_id,
    is_deleted,
    deleted_ymdhis,
    created_ymdhis,
    updated_ymdhis,
    semantic_weight,
    relationship_type,
    bidirectional,
    context_scope
)
SELECT
    'channel',
    9000,
    'content',
    c.content_id,
    'HAS_CONTENT',
    9000,
    'gov',
    0,
    0,
    1,
    0,
    0,
    CAST(DATE_FORMAT(FROM_UNIXTIME(UNIX_TIMESTAMP()), '%Y%m%d%H%i%S') AS UNSIGNED),
    CAST(DATE_FORMAT(FROM_UNIXTIME(UNIX_TIMESTAMP()), '%Y%m%d%H%i%S') AS UNSIGNED),
    0.00,
    'semantic',
    0,
    NULL
FROM lupo_contents c
WHERE c.slug IN (
    'architecture-canonical-ontology-architecture-governance-v1-0',
    'architecture-lupopedia-v4-0-70-agent-awareness-layer',
    'dev-teams-governance-gov-programmers-001',
    'dev-teams-governance-gov-toon-generation-001',
    'dev-teams-governance-gov-wolfie-headers-001',
    'dev-teams-governance-index',
    'dev-teams-governance-it-from-gov',
    'dev-teams-governance-overview',
    'dev-teams-governance-readme',
    'dev-teams-governance-registry',
    'dev-teams-governance-utc-day-governance',
    'doctrine-agent-awareness-doctrine',
    'doctrine-ai-integration-safety-doctrine',
    'doctrine-blocks-anchors-pattern-ethics-anchor',
    'doctrine-blocks-pattern-ethics-ethics-consent',
    'doctrine-blocks-pattern-ethics-ethics-reciprocity',
    'doctrine-blocks-pattern-ethics-ethics-transparency',
    'doctrine-blocks-pattern-ethics-pattern-exploitation-forbidden',
    'doctrine-blocks-pattern-ethics-pattern-tracking-required',
    'doctrine-crafty-syntax-migration-doctrine',
    'doctrine-cursor-context-metadata',
    'doctrine-database-security-doctrine',
    'doctrine-doctrine-emotional-logging',
    'doctrine-doctrine-versioning',
    'doctrine-emotional-agent-range',
    'doctrine-emotional-constitution',
    'doctrine-emotional-domains-seven-loves',
    'doctrine-emotional-ecology-layer',
    'doctrine-emotional-engine-specification-v2-0',
    'doctrine-emotional-geometry',
    'doctrine-emotional-geometry-three-axis-model-2026',
    'doctrine-ethical-foundations',
    'doctrine-gov-ad-prohibit-001',
    'doctrine-gov-anti-patterns-001',
    'doctrine-gov-appendix-a',
    'doctrine-gov-foundations',
    'doctrine-gov-integration-0001-witness-layer',
    'doctrine-gov-lilith-0001-dreaming-overlay',
    'doctrine-gov-prohibit-000',
    'doctrine-gov-prohibit-001',
    'doctrine-gov-prohibit-002',
    'doctrine-gov-prohibit-003',
    'doctrine-gov-prohibit-004',
    'doctrine-gov-prohibit-005',
    'doctrine-gov-prohibit-006',
    'doctrine-gov-prohibit-007',
    'doctrine-gov-prohibit-ads-001',
    'doctrine-gov-psychological-framing-prohibit-001',
    'doctrine-guardrails',
    'doctrine-legacy-core-metadata-governance',
    'doctrine-legacy-import-aal-v3-epistemic-pluralism',
    'doctrine-legacy-import-crafty-syntax-pattern-library',
    'doctrine-legacy-import-deprecated-deprecated-emotional-geometry',
    'doctrine-legacy-import-emotional-geometry-doctrine',
    'doctrine-legacy-import-emotional-topology-layer',
    'doctrine-legacy-import-ethical-foundations',
    'doctrine-legacy-import-year-based-versioning-doctrine',
    'doctrine-lupopedia-actor-baseline-state-doctrine',
    'doctrine-meta-agents',
    'doctrine-metadata-governance',
    'doctrine-migration-doctrine',
    'doctrine-migration-orchestrator-doctrine',
    'doctrine-no-foreign-keys-doctrine',
    'doctrine-no-stored-procedures-doctrine',
    'doctrine-no-triggers-doctrine',
    'doctrine-no-triggers-no-procedures-doctrine',
    'doctrine-operator-registry-doctrine',
    'doctrine-pack-role-registry',
    'doctrine-pattern-ethics-doctrine',
    'doctrine-pt-001-pattern-tracking-checksum',
    'doctrine-reflective-emotional-geometry-doctrine',
    'doctrine-saturday-governance-protocol-v1-0',
    'doctrine-system-agent-safety-doctrine',
    'doctrine-table-count-doctrine',
    'doctrine-version-control-policy',
    'doctrine-versioning-doctrine',
    'overview-privacy-policy'
)
AND NOT EXISTS (
    SELECT 1
    FROM lupo_edges e
    WHERE e.left_object_type = 'channel'
      AND e.left_object_id = 9000
      AND e.right_object_type = 'content'
      AND e.right_object_id = c.content_id
      AND e.edge_type = 'HAS_CONTENT'
);
