INSERT INTO lupo_channels (
    channel_id,
    federation_node_id,
    created_by_actor_id,
    default_actor_id,
    channel_key,
    channel_slug,
    channel_type,
    language,
    channel_name,
    description,
    metadata_json,
    bgcolor,
    status_flag,
    end_ymdhis,
    duration_seconds,
    created_ymdhis,
    updated_ymdhis,
    is_deleted,
    deleted_ymdhis,
    aal_metadata_json,
    fleet_composition_json,
    awareness_version,
    channel_number,
    parent_channel_id,
    is_kernel,
    boot_sequence_order
) VALUES (
    9000,
    1,
    1,
    1,
    'gov',
    'gov',
    'governance',
    'en',
    'Governance Channel',
    'System-wide governance, ethical triad, kapu rules, AAL versioning, fleet composition, and constitutional doctrine.',
    '{}',
    'FFFFFF',
    1,
    NULL,
    NULL,
    CAST(DATE_FORMAT(FROM_UNIXTIME(UNIX_TIMESTAMP()), '%Y%m%d%H%i%S') AS UNSIGNED),
    CAST(DATE_FORMAT(FROM_UNIXTIME(UNIX_TIMESTAMP()), '%Y%m%d%H%i%S') AS UNSIGNED),
    0,
    NULL,
    '{}',
    '{}',
    '1',
    9000,
    NULL,
    0,
    NULL
);
