-- Seed: lupo_projects (4.0.76). Run after install. project_id application-assigned, no AUTO_INCREMENT.
-- See PROJECT_REGISTRY_SCHEMA_DESIGN.md, create_lupo_projects.sql.md.

INSERT INTO lupo_projects (
  project_id,
  project_key,
  project_slug,
  project_name,
  federation_node_id,
  default_channel_id,
  orchestrator_id,
  project_type,
  description,
  status,
  is_active,
  is_deleted,
  is_archived,
  is_frozen,
  metadata_json,
  created_ymdhis,
  updated_ymdhis,
  deleted_ymdhis,
  created_by_actor_id,
  updated_by_actor_id
) VALUES (
  1,
  'lupopedia-core',
  'lupopedia-core',
  'Lupopedia Core Development',
  1,
  42,
  1,
  'standard',
  'Primary Lupopedia semantic OS instance; default development project.',
  'active',
  1,
  0,
  0,
  0,
  NULL,
  20260316000000,
  20260316000000,
  0,
  NULL,
  NULL
);
