-- =============================================================
-- Missing tables for semantic navbar / The Eye widget (4.0.94)
-- =============================================================
-- These tables exist in the live database (confirmed via TOON JSONs)
-- but are absent from install_new_lupopedia.sql.
--
-- Action required:
--   1. Review this file
--   2. Apply each CREATE TABLE block to install_new_lupopedia.sql
--      in the appropriate section (after lupo_paths_summary)
--   3. Regenerate TOON files: python lupo-scripts/generate_toon_files.py
--   4. Create table docs in lupo-docs/database/lupopedia/tables/active/
--
-- Rules:
--   - No AUTO_INCREMENT (PKs generated by IdGenerator::generate() in PHP)
--   - No UNSIGNED, ENGINE=, COLLATE=, FOREIGN KEY, triggers, procedures
--   - All timestamps BIGINT YYYYMMDDHHIISS UTC
--   - Soft delete: is_deleted TINYINT + deleted_ymdhis BIGINT
--   - {{prefix}} placeholder used for table prefix
-- =============================================================


-- -------------------------------------------------------------
-- lupo_paths
-- Aggregated navigation flows. Populated by gc.php from lupo_visits.
-- year_num/month_num/day_num for time-based partitioning.
-- entercontentid/exitcontentid are the core columns for prev/next page queries.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}paths (
  path_id bigint NOT NULL,
  entercontentid bigint DEFAULT NULL,
  exitcontentid bigint DEFAULT NULL,
  enter_table varchar(255) DEFAULT NULL,
  exit_table varchar(255) DEFAULT NULL,
  year_num int DEFAULT NULL,
  month_num int DEFAULT NULL,
  day_num int DEFAULT NULL,
  count_num int NOT NULL DEFAULT 0,
  transition_type varchar(64) DEFAULT NULL,
  transition_metadata text,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  updated_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (path_id)
);
CREATE INDEX {{prefix}}paths_idx_enter_exit ON {{prefix}}paths (entercontentid, exitcontentid);
CREATE INDEX {{prefix}}paths_idx_ymd ON {{prefix}}paths (year_num, month_num, day_num);
CREATE INDEX {{prefix}}paths_idx_transition ON {{prefix}}paths (transition_type);
CREATE INDEX {{prefix}}paths_idx_created ON {{prefix}}paths (created_ymdhis);
CREATE INDEX {{prefix}}paths_idx_is_deleted ON {{prefix}}paths (is_deleted);


-- -------------------------------------------------------------
-- lupo_references
-- Citation and source link records for the semantic navbar References section.
-- source_entity_type + source_entity_id identify the owning entity.
-- Linked to objects via lupo_reference_links.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}references (
  reference_id bigint NOT NULL,
  source_entity_type varchar(64) NOT NULL,
  source_entity_id bigint NOT NULL,
  url varchar(2000) DEFAULT NULL,
  title varchar(500) DEFAULT NULL,
  citation_text text,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  updated_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (reference_id)
);
CREATE INDEX {{prefix}}references_idx_source ON {{prefix}}references (source_entity_type, source_entity_id);
CREATE INDEX {{prefix}}references_idx_created ON {{prefix}}references (created_ymdhis);
CREATE INDEX {{prefix}}references_idx_is_deleted ON {{prefix}}references (is_deleted);


-- -------------------------------------------------------------
-- lupo_reference_links
-- Junction table linking lupo_references to objects (content, artifact, etc.).
-- object_type + object_id is the polymorphic target.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}reference_links (
  reference_link_id bigint NOT NULL,
  reference_id bigint NOT NULL,
  object_type varchar(64) NOT NULL,
  object_id bigint NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (reference_link_id)
);
CREATE INDEX {{prefix}}reference_links_idx_reference ON {{prefix}}reference_links (reference_id);
CREATE INDEX {{prefix}}reference_links_idx_object ON {{prefix}}reference_links (object_type, object_id);
CREATE INDEX {{prefix}}reference_links_idx_is_deleted ON {{prefix}}reference_links (is_deleted);


-- -------------------------------------------------------------
-- lupo_hashtags
-- Normalized hashtag registry. tag_slug is unique.
-- use_count is a denormalized cache updated by application logic.
-- Linked to objects via lupo_hashtag_map.
-- Do NOT use lupo_metadata or lupo_contents.hashtags JSON for new tag work.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}hashtags (
  hashtag_id bigint NOT NULL,
  tag_slug varchar(128) NOT NULL,
  label varchar(255) DEFAULT NULL,
  use_count bigint NOT NULL DEFAULT 0,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  updated_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (hashtag_id)
);
CREATE UNIQUE INDEX {{prefix}}hashtags_uniq_slug ON {{prefix}}hashtags (tag_slug);
CREATE INDEX {{prefix}}hashtags_idx_use_count ON {{prefix}}hashtags (use_count);
CREATE INDEX {{prefix}}hashtags_idx_is_deleted ON {{prefix}}hashtags (is_deleted);


-- -------------------------------------------------------------
-- lupo_hashtag_map
-- Junction table linking lupo_hashtags to objects.
-- object_type + object_id is the polymorphic target.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}hashtag_map (
  hashtag_map_id bigint NOT NULL,
  hashtag_id bigint NOT NULL,
  object_type varchar(64) NOT NULL,
  object_id bigint NOT NULL,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (hashtag_map_id)
);
CREATE INDEX {{prefix}}hashtag_map_idx_hashtag ON {{prefix}}hashtag_map (hashtag_id);
CREATE INDEX {{prefix}}hashtag_map_idx_object ON {{prefix}}hashtag_map (object_type, object_id);
CREATE INDEX {{prefix}}hashtag_map_idx_is_deleted ON {{prefix}}hashtag_map (is_deleted);


-- -------------------------------------------------------------
-- lupo_folders
-- Folder entities for folder-based grouping in the semantic navbar.
-- Supports hierarchy via parent_folder_id (self-referential, no DB FK).
-- Linked to objects via lupo_folder_map.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}folders (
  folder_id bigint NOT NULL,
  name varchar(255) NOT NULL,
  slug varchar(128) NOT NULL,
  parent_folder_id bigint DEFAULT NULL,
  actor_id bigint DEFAULT NULL,
  channel_id bigint DEFAULT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  updated_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (folder_id)
);
CREATE INDEX {{prefix}}folders_idx_parent ON {{prefix}}folders (parent_folder_id);
CREATE INDEX {{prefix}}folders_idx_actor ON {{prefix}}folders (actor_id);
CREATE INDEX {{prefix}}folders_idx_channel ON {{prefix}}folders (channel_id);
CREATE INDEX {{prefix}}folders_idx_slug ON {{prefix}}folders (slug);
CREATE INDEX {{prefix}}folders_idx_is_deleted ON {{prefix}}folders (is_deleted);


-- -------------------------------------------------------------
-- lupo_folder_map
-- Junction table linking lupo_folders to objects.
-- object_type + object_id is the polymorphic target.
-- -------------------------------------------------------------
CREATE TABLE {{prefix}}folder_map (
  folder_map_id bigint NOT NULL,
  folder_id bigint NOT NULL,
  object_type varchar(64) NOT NULL,
  object_id bigint NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  created_ymdhis bigint NOT NULL DEFAULT 0,
  is_deleted tinyint NOT NULL DEFAULT 0,
  deleted_ymdhis bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (folder_map_id)
);
CREATE INDEX {{prefix}}folder_map_idx_folder ON {{prefix}}folder_map (folder_id);
CREATE INDEX {{prefix}}folder_map_idx_object ON {{prefix}}folder_map (object_type, object_id);
CREATE INDEX {{prefix}}folder_map_idx_is_deleted ON {{prefix}}folder_map (is_deleted);
