#!/usr/bin/env python3
# ---------------------------------------------------------------------
# lupopedia.headers:
#   header_format_version: "4.1.1"
#   file_path_from_root: "lupo-scripts/generate_seed_sql_from_atom.py"
#   web_path: "https://www.lupopedia.com/lupopedia/lupo-scripts/generate_seed_sql_from_atom.py"
#   status: "active"
#   when_updated: "20260415152123"
#   trust_tier: "canonical"
#   questions_toon: null
#   memory_toon: "lupo-memory/development/canonical/1026/04/generate-seed-sql-from-atom.toon"
#   atoms_toon: "lupo-memory/atoms/lupopedia_global_constants.atom.toon"
#   transcript_jsonl: "0/development/generate-seed-sql-from-atom"
#   artifact_type: implementation
#   artifact_kind: tool
#   channel_key: "development"
#   federation_node_id: 0
#   thread_id: ""
#   content_id: null
#   content_parent_id: null
#   content_slug: "generate-seed-sql-from-atom"
#   default_collection_id: null
#   lupopedia.schema: implementation
#   title: "Generate SQL constants from global atom"
#   summary: "Reads global constants atom and emits deterministic SQL constant declarations for seed/install alignment."
# ---------------------------------------------------------------------

"""
Generate SQL constants from the global constants atom.

This script intentionally emits a deterministic SQL constants block rather than
direct table DML. The goal is to keep actor/trust/header constants aligned with
the atom without making unsafe schema assumptions.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone


def utc_ymdhis() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


def to_sql_var_name(prefix: str, key: str) -> str:
    safe = "".join(ch if ch.isalnum() else "_" for ch in key).upper()
    return "@%s_%s" % (prefix, safe)


def render_sql(atom_path: str, atom_data: dict) -> str:
    constants = atom_data.get("constants", {})
    actors = constants.get("actors", {})
    agents = constants.get("agents", {})
    trust_tiers = constants.get("trust_tiers", {})
    year_offset = constants.get("year_offset", {})
    header_fields = constants.get("header_fields", {})

    out = []
    out.append("-- Generated by generate_seed_sql_from_atom.py")
    out.append("-- Source atom: %s" % atom_path.replace("\\", "/"))
    out.append("-- Generated UTC: %s" % utc_ymdhis())
    out.append("")

    out.append("-- Actor IDs")
    for name, actor_id in sorted(actors.items(), key=lambda item: int(item[1])):
        out.append("SET %s = %s;" % (to_sql_var_name("ACTOR", name), int(actor_id)))
    out.append("")

    out.append("-- Agent IDs")
    for name, agent_id in sorted(agents.items(), key=lambda item: int(item[1])):
        out.append("SET %s = %s;" % (to_sql_var_name("AGENT", name), int(agent_id)))
    out.append("")

    out.append("-- Trust tier constants")
    for tier_name, tier_value in trust_tiers.items():
        out.append("SET %s = %s;" % (to_sql_var_name("TRUST", tier_name), int(tier_value)))
    out.append("")

    canonical_offset = year_offset.get("canonical_offset")
    if canonical_offset is not None:
        out.append("-- Year offset constants")
        out.append("SET @YEAR_OFFSET_CANONICAL = %s;" % int(canonical_offset))
        out.append("")

    header_count = header_fields.get("count")
    header_order = header_fields.get("order")
    if header_count is not None:
        out.append("-- Header constants")
        out.append("SET @HEADER_FIELDS_COUNT = %s;" % int(header_count))
        if isinstance(header_order, list):
            header_order_str = ",".join(str(x) for x in header_order)
            out.append("SET @HEADER_FIELDS_ORDER = '%s';" % header_order_str.replace("'", "''"))
        out.append("")

    out.append("-- End generated constants block")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate SQL constants from Lupopedia global atom."
    )
    parser.add_argument("--atom", required=True, help="Path to *.atom.toon constants file")
    parser.add_argument("--output", required=True, help="Path to write generated SQL")
    args = parser.parse_args()

    atom_path = os.path.abspath(args.atom)
    output_path = os.path.abspath(args.output)

    if not os.path.isfile(atom_path):
        print("[ERROR] Atom file not found: %s" % atom_path)
        return 1

    try:
        with open(atom_path, "r", encoding="utf-8") as f:
            atom_data = json.load(f)
    except Exception as exc:
        print("[ERROR] Failed to read atom JSON: %s" % exc)
        return 1

    if not isinstance(atom_data, dict):
        print("[ERROR] Atom must be a JSON object")
        return 1

    sql_text = render_sql(atom_path, atom_data)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="\n") as out:
        out.write(sql_text)

    print("[OK] Wrote SQL constants to %s" % output_path.replace("\\", "/"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
