-- ============================================================================
-- Migration: Kapu Protocol Tables
-- Date: 2026-01-30
-- Purpose: (DEPRECATED) Previously added lupo_operator_kapu_log and lupo_operator_escalations.
-- ============================================================================
-- Operator and role data now use channel-scoped role tables:
--   lupo_channel_roles — permission/role logic (captain, administrator, monitor per channel)
--   lupo_actor_channel_roles — protocol/awareness logic (AAL, RSHAP, CJP) when needed
-- The old operator tables (lupo_operators, lupo_operator_status, lupo_operator_kapu_log,
-- lupo_operator_escalations, etc.) are deprecated and have been removed from the schema.
-- Do not recreate them. Use lupo_channel_roles for operator/captain assignments.
-- ============================================================================
-- End of Migration
-- ============================================================================
