-- Migration: Backup Table with _old Suffix
-- Version: 4.1.1
-- Date: 2026-01-18
-- Module: Schema Backup
--
-- This migration documents the backup of a table by renaming it with _old suffix.
-- This preserves the original table structure and data before schema changes.
--
-- @package Lupopedia
-- @version 4.1.1
-- @author Captain Wolfie

-- ============================================================================
-- TABLE BACKUP OPERATION
-- ============================================================================
-- 
-- Backup Strategy:
--   - Original table renamed to {table_name}_old
--   - New table created with updated schema
--   - Data can be migrated from _old table if needed
--   - _old table can be dropped after verification
--
-- Example:
--   RENAME TABLE lupo_help_topics TO lupo_help_topics_old;
--   -- Then create new lupo_help_topics with updated schema
--
-- ============================================================================
-- BACKUP VERIFICATION
-- ============================================================================
-- 
-- To verify the backup table exists:
--   SHOW TABLES LIKE '%_old';
--
-- To compare row counts:
--   SELECT 
--       (SELECT COUNT(*) FROM lupo_help_topics) AS new_table_count,
--       (SELECT COUNT(*) FROM lupo_help_topics_old) AS old_table_count;
--
-- To verify structure differences:
--   DESCRIBE lupo_help_topics;
--   DESCRIBE lupo_help_topics_old;
--
-- ============================================================================
-- DATA MIGRATION (if needed)
-- ============================================================================
-- 
-- If data needs to be migrated from _old to new table:
-- 
-- INSERT INTO lupo_help_topics (
--     help_topic_id, slug, title, content_html, category,
--     created_ymdhis, updated_ymdhis, is_deleted, deleted_ymdhis
-- )
-- SELECT 
--     help_topic_id, slug, title, content_html, category,
--     created_ymdhis, updated_ymdhis, is_deleted, deleted_ymdhis
-- FROM lupo_help_topics_old
-- WHERE is_deleted = 0;  -- Only migrate active records
--
-- ============================================================================
-- CLEANUP (after verification)
-- ============================================================================
-- 
-- After verifying the new table works correctly and data is migrated:
-- 
-- DROP TABLE IF EXISTS lupo_help_topics_old;
--
-- WARNING: Only drop _old table after:
--   1. New table is verified working
--   2. Data migration is complete (if needed)
--   3. Application is tested with new schema
--   4. Backup is confirmed in version control
--
-- ============================================================================
-- NOTES
-- ============================================================================
-- 
-- - _old tables are temporary backups, not permanent archives
-- - Keep _old tables until new schema is fully verified
-- - Document which table was backed up and why
-- - Update TOON files to reflect new schema (not _old table)
--
-- Status: Backup completed - _old table preserved for rollback if needed
