-- Migration: Extend lupo_edges for FLARE file relationships
-- Date: 2026-02-27
-- Purpose: Add FLARE-specific fields to existing lupo_edges table
-- Note: This extends the canonical lupo_edges table (not lupo_relationships)
-- Reason: lupo_edges is the primary relationship table in Lupopedia
-- Compliance: Follows table ceiling doctrine by extending existing table

-- Add FLARE-specific columns to lupo_edges
ALTER TABLE lupo_edges 
ADD COLUMN flare_weight DECIMAL(3,2) DEFAULT 0.5 COMMENT 'FLARE edge weight (0.5-1.0)',
ADD COLUMN flare_reason VARCHAR(255) DEFAULT NULL COMMENT 'Reason for edge existence',
ADD COLUMN flare_db_source VARCHAR(50) DEFAULT NULL COMMENT 'Database source table',
ADD COLUMN flare_auto_generated TINYINT(1) DEFAULT 0 COMMENT 'Generated by automation',
ADD COLUMN flare_verified TINYINT(1) DEFAULT 0 COMMENT 'Path verified to exist',
ADD COLUMN flare_discovered_via VARCHAR(50) DEFAULT NULL COMMENT 'Discovery method';

-- Add indexes for FLARE file relationship queries
CREATE INDEX idx_lupo_edges_flare_files ON lupo_edges (left_object_type, left_object_id, edge_type, right_object_type, right_object_id);
CREATE INDEX idx_lupo_edges_flare_weight ON lupo_edges (flare_weight, edge_type);
CREATE INDEX idx_lupo_edges_flare_discovered ON lupo_edges (flare_discovered_via, flare_auto_generated);

-- Add FLARE-specific relationship types (these will be used in edge_type field)
-- Note: These are documented for reference - actual values stored in edge_type column
-- FLARE edge types:
-- - references (0.5-1.0)
-- - implements (0.8-1.0) 
-- - schema_reference (1.0)
-- - table_relationship (0.7-0.9)
-- - api_reference (0.8-1.0)
-- - ui_reference (0.6-0.9)
-- - migration_reference (0.7-0.9)
-- - test_reference (0.6-0.8)
-- - supersedes (0.9-1.0)
-- - depends_on (0.8-1.0)
-- - example_of (0.6-0.8)
-- - related_to (0.5-0.7)

-- Add FLARE source types for file relationships
-- FLARE source types:
-- - file (for .md files)
-- - toon (for TOON schema files)
-- - actor (for actor references)
-- - channel (for channel references)

-- Sample FLARE relationship insertions (for reference):
-- Note: Uses lupo_edges table structure with left/right objects
INSERT INTO lupo_edges (left_object_type, left_object_id, edge_type, right_object_type, right_object_id, flare_weight, flare_reason, flare_db_source, flare_auto_generated, flare_verified, flare_discovered_via, created_ymdhis, updated_ymdhis) VALUES
('file', 1, 'references', 'file', 2, 1.0, 'Primary reference', 'lupo_contents', 1, 1, 'content_analysis', 20260227120000, 20260227120000),
('file', 1, 'schema_reference', 'toon', 1, 1.0, 'Table schema reference', 'lupo_dialog_messages', 1, 1, 'toon_schema', 20260227120000, 20260227120000);

-- Note: File IDs should reference lupo_contents table where content_type = 'file'
-- TOON IDs reference specific TOON files (may need lupo_contents entries for TOON files)
