-- One-time development migration: rename reserved-word columns.
-- Canonical schema: database/migrations/install_new_lupopedia.sql
-- Doctrine: no UNSIGNED, no display widths, no FK/triggers; quote column names.
-- Do NOT modify TOONs; they will be regenerated by the user.

-- 1. lupo_actor_group_membership: role -> role_key
ALTER TABLE lupo_actor_group_membership
  CHANGE COLUMN `role` `role_key` varchar(50) DEFAULT 'member';

-- 2. lupo_artifacts: type -> entity_type (drop index first, add after)
ALTER TABLE lupo_artifacts DROP INDEX lupo_artifacts_idx_type;
ALTER TABLE lupo_artifacts
  CHANGE COLUMN `type` `entity_type` varchar(64) NOT NULL;
ALTER TABLE lupo_artifacts ADD INDEX lupo_artifacts_idx_entity_type (`entity_type`);

-- 3. lupo_pack_role_registry: role -> role_key (drop index first, add after)
ALTER TABLE lupo_pack_role_registry DROP INDEX lupo_pack_role_registry_idx_role;
ALTER TABLE lupo_pack_role_registry
  CHANGE COLUMN `role` `role_key` varchar(255) NOT NULL;
ALTER TABLE lupo_pack_role_registry ADD INDEX lupo_pack_role_registry_idx_role_key (`role_key`);

-- 4. lupo_unified_analytics_paths: year_month -> year_month_key
ALTER TABLE lupo_unified_analytics_paths
  CHANGE COLUMN `year_month` `year_month_key` char(6) NOT NULL;
