<?php
/**
 * Install-time Apache hardening and rewrite rules (Softaculous / FTP-safe packages).
 *
 * Distribution archives omit ALL dotfiles (including .htaccess) so FTP clients do not skip them.
 * This class writes the same rules as the development tree after a successful config step.
 *
 * Nginx and IIS do not use .htaccess; operators must map rules in server config (see SOFTACULOUS_PACKAGE_BUILD.md).
 *
 * PHP 5.3+ compatible.
 *
 * @package Lupopedia
 */

if (!defined('LUPOPEDIA_PATH')) {
    return;
}

class InstallWizardHtaccessWriter
{

    /**
     * Inner Apache rules only (no BEGIN/END markers). Must stay aligned with repo root .htaccess.
     *
     * @return string
     */
    public static function getRootHtaccessBody()
    {
        return <<<'LUPOHTA'
# Lupopedia .htaccess
# Generated by install wizard — no mod_rewrite front-controller routing (use index.php?slug=…, login.php, …).

# Default document
DirectoryIndex index.php index.html

# Prevent directory listing
Options -Indexes

# Security Headers
<IfModule mod_headers.c>
    Header set X-Content-Type-Options "nosniff"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-XSS-Protection "1; mode=block"
</IfModule>

# Security: Deny access to hidden files
<FilesMatch "^\.">
    Order allow,deny
    Deny from all
</FilesMatch>

# Deny access to config files
<FilesMatch "^(lupopedia-config\.php|\.htaccess)$">
    Order allow,deny
    Deny from all
</FilesMatch>

# Prevent access to sensitive file types in webroot
<FilesMatch "\.(sql|log|md|yaml|yml|json|bak|backup|old)$">
    Order allow,deny
    Deny from all
</FilesMatch>
LUPOHTA;
    }

    /**
     * Root rules wrapped for marker-based merge (WordPress-style).
     *
     * @return string
     */
    public static function getRootHtaccessMarkedBlock()
    {
        return '# BEGIN LUPOPEDIA' . "\n" . self::getRootHtaccessBody() . "\n" . '# END LUPOPEDIA' . "\n";
    }

    /**
     * Deny web access to SQL and seeds under lupo-database/ (aligned with repo lupo-database/.htaccess).
     *
     * @return string
     */
    public static function getDatabaseDirHtaccessBody()
    {
        return <<<'LUPOHTADB'
# Protect database configuration, schema, seeds, and derived files
# Prevents direct download of sensitive files over the web
# Local PHP execution via require/include/fopen is unaffected.

<IfModule mod_authz_core.c>
    # Apache 2.4+
    Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
    # Apache 2.2
    Order allow,deny
    Deny from all
</IfModule>
LUPOHTADB;
    }

    /**
     * Database directory deny rules wrapped for marker-based merge.
     *
     * @return string
     */
    public static function getDatabaseDirHtaccessMarkedBlock()
    {
        return '# BEGIN LUPOPEDIA_DB' . "\n" . self::getDatabaseDirHtaccessBody() . "\n" . '# END LUPOPEDIA_DB' . "\n";
    }

    /**
     * True when .htaccess is meaningful (Apache, LiteSpeed). False for Nginx/IIS/Caddy, etc.
     *
     * @return bool
     */
    public static function isApacheHtaccessEnvironment()
    {
        $sw = '';
        if (isset($_SERVER['SERVER_SOFTWARE']) && is_string($_SERVER['SERVER_SOFTWARE'])) {
            $sw = $_SERVER['SERVER_SOFTWARE'];
        }
        $sl = strtolower($sw);
        if ($sl === '') {
            return true;
        }
        if (strpos($sl, 'nginx') !== false) {
            return false;
        }
        if (strpos($sl, 'microsoft-iis') !== false || strpos($sl, 'iis/') !== false) {
            return false;
        }
        if (strpos($sl, 'caddy') !== false) {
            return false;
        }
        if (strpos($sl, 'apache') !== false || strpos($sl, 'litespeed') !== false) {
            return true;
        }
        return false;
    }

    /**
     * Replace or append a single marked block; preserve all content outside markers.
     *
     * @param string $existing
     * @param string $insertion full block including # BEGIN / # END lines
     * @param string $marker token after BEGIN/END (e.g. LUPOPEDIA)
     * @return string
     */
    public static function insertWithMarkers($existing, $insertion, $marker)
    {
        $begin = '# BEGIN ' . $marker;
        $end = '# END ' . $marker;
        $pattern = '/' . preg_quote($begin, '/') . '\s*.*?' . preg_quote($end, '/') . '\s*/s';
        $insertionTrim = rtrim($insertion, "\r\n") . "\n";
        if ($existing === null || $existing === false) {
            $existing = '';
        }
        if (preg_match($pattern, $existing)) {
            return preg_replace($pattern, $insertionTrim, $existing, 1);
        }
        if ($existing === '') {
            return $insertionTrim;
        }
        $trimmed = rtrim($existing, "\r\n");
        $sep = (substr($trimmed, -1) === "\n" || $trimmed === '') ? "\n" : "\n\n";
        return $trimmed . $sep . $insertionTrim;
    }

    /**
     * Normalize line endings and outer whitespace for .htaccess body comparison.
     *
     * @param string $s
     * @return string
     */
    private static function normalizeHtaccessWhitespace($s)
    {
        return trim(str_replace(array("\r\n", "\r"), "\n", $s));
    }

    /**
     * If file has no marker block but matches the shipped inner body, treat as empty so we only write the marked block once.
     *
     * @param string $existing
     * @param string $marker
     * @param string $canonicalInner from getRootHtaccessBody() or getDatabaseDirHtaccessBody()
     * @return string
     */
    private static function stripLegacyUnmarkedBody($existing, $marker, $canonicalInner)
    {
        $beginToken = '# BEGIN ' . $marker;
        if (strpos($existing, $beginToken) !== false) {
            return $existing;
        }
        if (self::normalizeHtaccessWhitespace($existing) === self::normalizeHtaccessWhitespace($canonicalInner)) {
            return '';
        }
        return $existing;
    }

    /**
     * Create writable runtime dirs (no .gitkeep in distribution packages).
     *
     * @param string $lupopediaPath
     * @param array $writeLog
     * @return void
     */
    public static function ensureRuntimeDirectories($lupopediaPath, &$writeLog)
    {
        $dirs = array('lupo-cache', 'lupo-logs', 'lupo-uploads', 'lupo-tmp');
        foreach ($dirs as $dir) {
            $path = rtrim($lupopediaPath, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $dir;
            if (is_dir($path)) {
                continue;
            }
            if (@mkdir($path, 0755, true)) {
                $writeLog[] = InstallWizardLogger::logEntry('ok', 'Created directory: ' . $dir . '/');
            } else {
                $writeLog[] = InstallWizardLogger::logEntry('warn', 'Could not create directory: ' . $dir . '/ (create manually with 0755).');
            }
        }
    }

    /**
     * Write root and lupo-database/.htaccess on Apache/LiteSpeed only; marker merge preserves manual rules.
     * Nginx/IIS: skip file writes; operators use server config (see SOFTACULOUS_PACKAGE_BUILD.md).
     *
     * @param string $lupopediaPath
     * @param array $writeLog
     * @return void
     */
    public static function writeDistributionHtaccess($lupopediaPath, &$writeLog)
    {
        $root = rtrim($lupopediaPath, DIRECTORY_SEPARATOR);

        if (!self::isApacheHtaccessEnvironment()) {
            $sw = '';
            if (isset($_SERVER['SERVER_SOFTWARE']) && is_string($_SERVER['SERVER_SOFTWARE'])) {
                $sw = $_SERVER['SERVER_SOFTWARE'];
            }
            $label = ($sw !== '') ? $sw : 'unknown';
            $writeLog[] = InstallWizardLogger::logEntry(
                'warn',
                'Skipped .htaccess generation: SERVER_SOFTWARE (' . $label . ') is not Apache/LiteSpeed. Configure rewrites and deny rules in Nginx/IIS (see SOFTACULOUS_PACKAGE_BUILD.md and README).'
            );
            return;
        }

        $rootFile = $root . DIRECTORY_SEPARATOR . '.htaccess';
        $existingRoot = '';
        if (is_file($rootFile) && is_readable($rootFile)) {
            $readRoot = @file_get_contents($rootFile);
            if ($readRoot !== false) {
                $existingRoot = $readRoot;
            }
        }
        $existingRoot = self::stripLegacyUnmarkedBody($existingRoot, 'LUPOPEDIA', self::getRootHtaccessBody());
        $mergedRoot = self::insertWithMarkers($existingRoot, self::getRootHtaccessMarkedBlock(), 'LUPOPEDIA');
        if (self::atomicWrite($rootFile, $mergedRoot)) {
            $writeLog[] = InstallWizardLogger::logEntry('ok', 'Wrote Apache rewrite file: .htaccess (document root; # BEGIN LUPOPEDIA marker merge).');
        } else {
            $writeLog[] = InstallWizardLogger::logEntry('warn', 'Could not write .htaccess in document root. On Apache, add rewrite rules manually; on Nginx/IIS use server config (see hosting documentation).');
        }

        $dbDir = $root . DIRECTORY_SEPARATOR . 'lupo-database';
        if (!is_dir($dbDir)) {
            $writeLog[] = InstallWizardLogger::logEntry('warn', 'lupo-database/ missing; skipped database directory .htaccess.');
            return;
        }
        $dbFile = $dbDir . DIRECTORY_SEPARATOR . '.htaccess';
        $existingDb = '';
        if (is_file($dbFile) && is_readable($dbFile)) {
            $readDb = @file_get_contents($dbFile);
            if ($readDb !== false) {
                $existingDb = $readDb;
            }
        }
        $existingDb = self::stripLegacyUnmarkedBody($existingDb, 'LUPOPEDIA_DB', self::getDatabaseDirHtaccessBody());
        $mergedDb = self::insertWithMarkers($existingDb, self::getDatabaseDirHtaccessMarkedBlock(), 'LUPOPEDIA_DB');
        if (self::atomicWrite($dbFile, $mergedDb)) {
            $writeLog[] = InstallWizardLogger::logEntry('ok', 'Wrote Apache deny rules: lupo-database/.htaccess (# BEGIN LUPOPEDIA_DB marker merge).');
        } else {
            $writeLog[] = InstallWizardLogger::logEntry('warn', 'Could not write lupo-database/.htaccess; block web access to SQL files in your server config.');
        }
    }

    /**
     * @param string $path
     * @param string $contents
     * @return bool
     */
    private static function atomicWrite($path, $contents)
    {
        if (!is_writable(dirname($path))) {
            return false;
        }
        $tmp = $path . '.tmp.' . (string) mt_rand(10000, 99999);
        $n = @file_put_contents($tmp, $contents, LOCK_EX);
        if ($n === false || $n !== strlen($contents)) {
            @unlink($tmp);
            return false;
        }
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            return false;
        }
        return true;
    }
}
